class_name GameplayEventTypes
extends RefCounted

const NPC_TALKED := &"npc_talked"
const NPC_ATTACKED := &"npc_attacked"
const ITEM_GIVEN := &"item_given"
const ITEM_RECEIVED := &"item_received"
const ITEM_COLLECTED := &"item_collected"
const ITEM_REMOVED := &"item_removed"
const ITEM_DELIVERED := &"item_delivered"
const REGION_ENTERED := &"region_entered"
const ENTITY_INTERACTED := &"entity_interacted"
const ENTITY_DEFEATED := &"entity_defeated"
const ENTITY_DOWNED := &"entity_downed"
const RELATIONSHIP_CHANGED := &"relationship_changed"
const QUEST_STARTED := &"quest_started"
const QUEST_COMPLETED := &"quest_completed"
const QUEST_FAILED := &"quest_failed"
const ENTITY_DESTROYED := &"entity_destroyed"
const TRADE_COMPLETED := &"trade_completed"
const PROMISE_MADE := &"promise_made"
const WORLD_FLAG_CHANGED := &"world_flag_changed"
const TIME_REACHED := &"time_reached"
const PET_BOND_CHANGED := &"pet_bond_changed"
const MOUNT_UNLOCKED := &"mount_unlocked"
const LOCATION_EXPLORED := &"location_explored"
const ENCOUNTER_DISCOVERED := &"encounter_discovered"
